sudo: require
language: generic

services:
  - docker

before_install:
  - docker build -t welingtonfx/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true welingtonfx/docker-react npm run test
